# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connect < Formula
  desc "Dioad Connect is an SNI based TCP reverse tunnel that provides end-to-end encrypted traffic whereever you need it."
  homepage "https://dioad.com/"
  version "0.59.3"
  depends_on :macos

  url "http://releases.lab.dioad.net/data/connect/0.59.3/connect_darwin_all.tar.gz", using: CurlDownloadStrategy
  sha256 "1079b96f958c285208bde45d4e1f77d787ccc59687d0a4e1643dcdf244736ff6"

  def install
    bin.install "connect"
  end

  test do
    system "#{bin}/connect --version"
  end
end
