# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connect < Formula
  desc "Dioad Connect is an SNI based TCP reverse tunnel that provides end-to-end encrypted traffic whereever you need it."
  homepage "https://dioad.com/"
  version "0.71.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://releases.lab.dioad.net/data/connect/0.71.0/connect_darwin_amd64.zip", using: CurlDownloadStrategy
    sha256 "6a765270b6e4a4dc3d698bf2321c6d68d0e582c98f3fa452c0c9ff4d229f9b0b"

    define_method(:install) do
      bin.install "connect"
    end
  end
  if Hardware::CPU.arm?
    url "https://releases.lab.dioad.net/data/connect/0.71.0/connect_darwin_arm64.zip", using: CurlDownloadStrategy
    sha256 "66eb2fdf9b84621c53b89096de0cf9e4ba2a875919737ddc4803181d48409afd"

    define_method(:install) do
      bin.install "connect"
    end
  end

  test do
    system "#{bin}/connect --version"
  end
end
