# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connect < Formula
  desc "Dioad Connect is an SNI based TCP reverse tunnel that provides end-to-end encrypted traffic whereever you need it."
  homepage "https://dioad.com/"
  version "0.63.8"
  depends_on :macos

  on_intel do
    url "https://releases.lab.dioad.net/data/connect/0.63.8/connect_darwin_amd64.zip", using: CurlDownloadStrategy
    sha256 "490cee68c90b79973c3ed94571d81cdbac693150c66f5230f4bed1bc07e2ef0c"

    def install
      bin.install "connect"
    end
  end
  on_arm do
    url "https://releases.lab.dioad.net/data/connect/0.63.8/connect_darwin_arm64.zip", using: CurlDownloadStrategy
    sha256 "2e0f13d8d0ed173480529f66ab78922e601f0cc61fee03ed4a42e03b71bfec93"

    def install
      bin.install "connect"
    end
  end

  test do
    system "#{bin}/connect --version"
  end
end
