# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Connect < Formula
  desc "Dioad Connect is an SNI based TCP reverse tunnel that provides end-to-end encrypted traffic whereever you need it."
  homepage "https://dioad.com/"
  version "0.32.2"
  depends_on :macos

  on_macos do
    url "http://releases.lab.dioad.net/data/connect/0.32.2/connect_darwin_all.tar.gz", :using => CurlDownloadStrategy
    sha256 "c69baaef345c7622e1802b8909c71c9e015ef6d507670f55619c7401d162af91"

    def install
      bin.install "connect"
    end
  end

  test do
    system "#{bin}/connect --version"
  end
end
