# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eventbroker < Formula
  desc "HTTP event broker with CloudEvents, SSE, and webhook support"
  homepage "https://dioad.com/"
  version "0.2.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://releases.lab.dioad.net/data/eventbroker/0.2.3/eventbroker_darwin_amd64.zip", using: CurlDownloadStrategy
    sha256 "a63aa5c46b46918e2a40548503211f8fa971ff4b85c38783259a5362e56ccd4e"

    define_method(:install) do
      bin.install "eventbroker"
    end
  end
  if Hardware::CPU.arm?
    url "https://releases.lab.dioad.net/data/eventbroker/0.2.3/eventbroker_darwin_arm64.zip", using: CurlDownloadStrategy
    sha256 "dd28093e03136d36215d2592782ac87495687c53191893e4e10365d4a7419147"

    define_method(:install) do
      bin.install "eventbroker"
    end
  end

  test do
    system "#{bin}/eventbroker --version"
  end
end
