# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eventbroker < Formula
  desc "HTTP event broker with CloudEvents, SSE, and webhook support"
  homepage "https://dioad.com/"
  version "0.4.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://releases.lab.dioad.net/data/eventbroker/0.4.0/eventbroker_darwin_amd64.zip", using: CurlDownloadStrategy
    sha256 "38d9a3dd708af4490ca2318f79d4b88d684a5334903deab90b7ac356402af902"

    define_method(:install) do
      bin.install "eventbroker"
    end
  end
  if Hardware::CPU.arm?
    url "https://releases.lab.dioad.net/data/eventbroker/0.4.0/eventbroker_darwin_arm64.zip", using: CurlDownloadStrategy
    sha256 "eb88362387ea0cd63dba7462feb987948b8ee51f98f44f417c19fa81c25476d3"

    define_method(:install) do
      bin.install "eventbroker"
    end
  end

  test do
    system "#{bin}/eventbroker --version"
  end
end
