# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eventbroker < Formula
  desc "HTTP event broker with CloudEvents, SSE, and webhook support"
  homepage "https://dioad.com/"
  version "0.3.5"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://releases.lab.dioad.net/data/eventbroker/0.3.5/eventbroker_darwin_amd64.zip", using: CurlDownloadStrategy
    sha256 "ba28dbba0cd1b92c5773ab52bfadc70069b34b5101d1f78849d4ce14becead46"

    define_method(:install) do
      bin.install "eventbroker"
    end
  end
  if Hardware::CPU.arm?
    url "https://releases.lab.dioad.net/data/eventbroker/0.3.5/eventbroker_darwin_arm64.zip", using: CurlDownloadStrategy
    sha256 "09adb84796f257b463d83f6774011f1c801114c9528ff64a6160aae97b5ed36c"

    define_method(:install) do
      bin.install "eventbroker"
    end
  end

  test do
    system "#{bin}/eventbroker --version"
  end
end
